### ISSUE TITLE
Framework7 v3

### ISSUE THREAD

**Issue by J05HI** [JasonKleban/framework7-vue.d.ts#1]
@JasonKleban
Have you planned them for v3 too?

**Comment by JasonKleban** [comment]
I can't keep up.  I need them.  Vue.js and single file components are not typesafe-friendly (in my experience, but I wish to be convinced otherwise), single-file-components don't have good tooling support, and now there's a new Framework7-specific file format?  It's overwhelming.

**Comment by J05HI** [comment]
@JasonKleban
I've created an issue in the F7 repo and I got the answer that they'll add it soon.
